version: '3.8'

services:
  mysqldb:
    build: ./database
    container_name: mysqldb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_DATABASE: customers
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - blood-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  app:
    build: .
    container_name: bloodbank-app
    restart: always
    ports:
      - "80:80"
    depends_on:
      mysqldb:
        condition: service_healthy
    environment:
      DB_HOST: mysqldb
      DB_USER: root
      DB_PASSWORD: admin123
      DB_NAME: customers
    volumes:
      - .:/var/www/html
    networks:
      - blood-network

volumes:
  db-data:

networks:
  blood-network:
    driver: bridge
